# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: "uv.lock"

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v22.1.5"
    hooks:
      - id: clang-format
        args: [ "--style=Microsoft", "-i" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.16
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: "1.1.0.dev1"
    hooks:
      - id: pyrefly-check
        name: Pyrefly (type checking)
        pass_filenames: true
        additional_dependencies: [ "numpy>=2.0.0", "pytest==9.0.1" ]
