#include "multipoleobject.h"
#include "allocator.h"
#include <numpy/arrayobject.h>
// this goes last
#include <cpyutl.h>

/*
 * ----------------------------------------------------------------
 *  Helpers
 * ----------------------------------------------------------------
 */

/**
 * @brief Type-check self and retrieve module state (bound-method helper).
 */
static bool ensure_multipole_and_state(PyTypeObject *defining_class, PyObject *self,
                                       const PyVL_MultipoleObject **p_this, const module_state_t **p_state)
{
    const module_state_t *state = NULL;
    if (defining_class)
        state = PyType_GetModuleState(defining_class);
    else
        state = get_module_state(Py_TYPE(self));

    if (!state)
        return false;

    if (!PyObject_TypeCheck(self, state->multipole_type))
    {
        PyErr_Format(PyExc_TypeError, "Self was not \"%s\" but was \"%s\".", state->multipole_type->tp_name,
                     Py_TYPE(self)->tp_name);
        return false;
    }
    *p_this = (const PyVL_MultipoleObject *)self;
    *p_state = state;
    return true;
}

/**
 * @brief Parse a VecLike3 argument into a real3_t.
 *
 * Accepts any (3,) contiguous double array-like.
 */
static bool pyvl_veclike3_to_real3(PyObject *obj, real3_t *out)
{
    PyArrayObject *arr =
        (PyArrayObject *)PyArray_FROMANY(obj, NPY_DOUBLE, 1, 1, NPY_ARRAY_C_CONTIGUOUS | NPY_ARRAY_ALIGNED);
    if (!arr)
        return false;
    if (PyArray_DIM(arr, 0) != 3)
    {
        PyErr_Format(PyExc_ValueError, "Expected a 3-element vector, got %" NPY_INTP_FMT " elements.",
                     PyArray_DIM(arr, 0));
        Py_DECREF(arr);
        return false;
    }
    const double *data = PyArray_DATA(arr);
    out->x = data[0];
    out->y = data[1];
    out->z = data[2];
    Py_DECREF(arr);
    return true;
}

/**
 * @brief Convert a (..., 3) array-like to a contiguous (N, 3) double array and return N.
 *
 * The caller owns the returned PyArrayObject reference.
 */
static PyArrayObject *pyvl_flatten_points(PyObject *obj, size_t *p_n)
{
    PyArrayObject *arr =
        (PyArrayObject *)PyArray_FROMANY(obj, NPY_DOUBLE, 2, INT_MAX, NPY_ARRAY_C_CONTIGUOUS | NPY_ARRAY_ALIGNED);
    if (!arr)
        return NULL;

    const int ndim = PyArray_NDIM(arr);
    if (PyArray_DIM(arr, ndim - 1) != 3)
    {
        PyErr_Format(PyExc_ValueError, "Last axis must have size 3, got %" NPY_INTP_FMT ".",
                     PyArray_DIM(arr, ndim - 1));
        Py_DECREF(arr);
        return NULL;
    }

    size_t n = 1;
    for (int i = 0; i < ndim - 1; ++i)
        n *= PyArray_DIM(arr, i);
    *p_n = n;
    return arr;
}

/**
 * @brief Allocate the 3-component coefficient buffer and set coeff pointers.
 *
 * Caller owns the returned buffer (must be freed with PyMem_Free).
 */
static double *pyvl_allocate_coeffs(unsigned order, multipole_t *mp)
{
    const size_t n_coeffs = multipole_num_coeffs(order);
    const size_t nbytes = sizeof(double) * 3 * n_coeffs;
    double *buf = (double *)PyMem_Malloc(nbytes);
    if (!buf)
    {
        PyErr_NoMemory();
        return NULL;
    }
    memset(buf, 0, nbytes);
    mp->coeffs_x = buf;
    mp->coeffs_y = buf + n_coeffs;
    mp->coeffs_z = buf + 2 * n_coeffs;
    return buf;
}

/*
 * ----------------------------------------------------------------
 *  tp_new / tp_init / tp_dealloc / tp_str / tp_richcompare
 * ----------------------------------------------------------------
 */

PyDoc_STRVAR(pyvl_multipole_type_docstring, "Multipole(order: int, center: VecLike3, /)\n"
                                            "Multipole expansion approximating the vector induction field\n"
                                            "generated by vortex particles.\n"
                                            "\n"
                                            "The multipole expansion approximates the induction field\n"
                                            "\n"
                                            ".. math::\n"
                                            "\n"
                                            "    \\vec{v}(\\vec{x}) = \\sum_{i=1}^{n}\n"
                                            "    \\frac{\\vec{\\Gamma}_i}\n"
                                            "    {|\\vec{r}_i - \\vec{x}|^2}\n"
                                            "\n"
                                            "as a low-order series expansion around a centre.\n"
                                            "\n"
                                            "Parameters\n"
                                            "----------\n"
                                            "order : int\n"
                                            "    Order of the multipole expansion (>= 0).\n"
                                            "center : VecLike3\n"
                                            "    Center of the expansion.\n"
                                            "\n"
                                            "See Also\n"
                                            "--------\n"
                                            "Multipole.from_sources : Construct and populate in one step.\n"
                                            "\n"
                                            "Examples\n"
                                            "--------\n"
                                            ">>> import numpy as np\n"
                                            ">>> from pyvl.cvl import Multipole\n"
                                            ">>> m = Multipole(2, (1.0, 0.0, 0.0))\n"
                                            ">>> m.order\n"
                                            "2\n"
                                            ">>> m.center\n"
                                            "array([1., 0., 0.])\n"
                                            "\n"
                                            "Build a multipole from random sources, evaluate on the ``z=0``\n"
                                            "plane and plot the field magnitude and relative error:\n"
                                            "\n"
                                            ".. jupyter-execute::\n"
                                            "\n"
                                            "    >>> import matplotlib.pyplot as plt\n"
                                            "    >>> import numpy as np\n"
                                            "    >>> from pyvl.cvl import Multipole\n"
                                            "    >>>\n"
                                            "    >>> rng = np.random.default_rng(42)\n"
                                            "    >>> pts = rng.uniform(-0.1, 0.1, size=(8, 3))\n"
                                            "    >>> vals = rng.uniform(-1, 1, size=(8, 3))\n"
                                            "    >>> mp = Multipole.from_sources(2, (0., 0., 0.), pts, vals)\n"
                                            "    >>>\n"
                                            "    >>> x = y = np.linspace(-5, 5, 100)\n"
                                            "    >>> xs, ys = np.meshgrid(x, y)\n"
                                            "    >>> points = np.stack([xs.ravel(), ys.ravel(),\n"
                                            "    ...                    np.zeros_like(xs.ravel())], axis=-1)\n"
                                            "    >>> v_app = mp.eval(points)\n"
                                            "    >>> v_ex = np.sum(vals[:, None] / np.maximum(\n"
                                            "    ...     np.sum((points[None] - pts[:, None]) ** 2,\n"
                                            "    ...            axis=-1, keepdims=True), 1e-300), axis=0)\n"
                                            "    >>>\n"
                                            "    >>> err = (np.linalg.norm(v_app - v_ex, axis=-1)\n"
                                            "    ...        / np.maximum(np.linalg.norm(v_ex, axis=-1), 1e-300))\n"
                                            "    >>>\n"
                                            "    >>> fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n"
                                            "    >>> mag = np.log10(np.maximum(\n"
                                            "    ...     np.linalg.norm(v_app, axis=-1), 1e-30))\n"
                                            "    >>> c1 = ax1.contourf(xs, ys, mag.reshape(xs.shape),\n"
                                            "    ...                    levels=20, cmap=\"viridis\")\n"
                                            "    >>> _ = ax1.set(title=\"$|\\\\mathbf{v}|$ (order 2)\",\n"
                                            "    ...         xlabel=\"$x$\", ylabel=\"$y$\")\n"
                                            "    >>> _ = fig.colorbar(c1, ax=ax1)\n"
                                            "    >>> c2 = ax2.contourf(xs, ys,\n"
                                            "    ...     np.log10(err.reshape(xs.shape)),\n"
                                            "    ...     levels=20, cmap=\"viridis\")\n"
                                            "    >>> _ = ax2.set(title=\"relative error\",\n"
                                            "    ...         xlabel=\"$x$\", ylabel=\"$y$\")\n"
                                            "    >>> _ = fig.colorbar(c2, ax=ax2)\n"
                                            "    >>> plt.show()\n");

static PyObject *pyvl_multipole_new(PyTypeObject *type, PyObject *args, PyObject *kwargs)
{
    PyVL_MultipoleObject *self = (PyVL_MultipoleObject *)type->tp_alloc(type, 0);
    if (!self)
        return NULL;

    self->coeff_buffer = NULL;
    self->multipole.order = 0;
    self->multipole.center = (real3_t){{0}};
    self->multipole.coeffs_x = NULL;
    self->multipole.coeffs_y = NULL;
    self->multipole.coeffs_z = NULL;

    unsigned order;
    PyObject *center_obj;
    if (!PyArg_ParseTupleAndKeywords(args, kwargs, "IO", (char *[3]){"order", "center", NULL}, &order, &center_obj))
    {
        Py_DECREF(self);
        return NULL;
    }

    if (!pyvl_veclike3_to_real3(center_obj, &self->multipole.center))
    {
        Py_DECREF(self);
        return NULL;
    }

    self->multipole.order = order;
    self->coeff_buffer = pyvl_allocate_coeffs(order, &self->multipole);
    if (!self->coeff_buffer)
    {
        Py_DECREF(self);
        return NULL;
    }

    return (PyObject *)self;
}

static void pyvl_multipole_dealloc(PyObject *self)
{
    PyObject_GC_UnTrack(self);
    PyVL_MultipoleObject *this = (PyVL_MultipoleObject *)self;
    PyMem_Free(this->coeff_buffer);
    this->coeff_buffer = NULL;
    PyTypeObject *type = Py_TYPE(self);
    type->tp_free(self);
    Py_DECREF(type);
}

static PyObject *pyvl_multipole_str(PyObject *self)
{
    const PyVL_MultipoleObject *this = (const PyVL_MultipoleObject *)self;
    char buf[128];
    snprintf(buf, sizeof(buf), "Multipole(%u, (%.4g, %.4g, %.4g))", this->multipole.order, this->multipole.center.x,
             this->multipole.center.y, this->multipole.center.z);
    return PyUnicode_FromString(buf);
}

static PyObject *pyvl_multipole_repr(PyObject *self)
{
    const PyVL_MultipoleObject *this = (const PyVL_MultipoleObject *)self;
    char buf[160];
    snprintf(buf, sizeof(buf), "<Multipole order=%u center=(%.4g, %.4g, %.4g) at %p>", this->multipole.order,
             this->multipole.center.x, this->multipole.center.y, this->multipole.center.z, (void *)self);
    return PyUnicode_FromString(buf);
}

static PyObject *pyvl_multipole_rich_compare(PyObject *self, PyObject *other, int op)
{
    const module_state_t *state = get_module_state(Py_TYPE(self));
    if (!state)
        return NULL;

    if (op != Py_EQ && op != Py_NE)
    {
        Py_RETURN_NOTIMPLEMENTED;
    }
    if (!PyObject_TypeCheck(other, state->multipole_type))
    {
        Py_RETURN_NOTIMPLEMENTED;
    }

    const PyVL_MultipoleObject *a = (const PyVL_MultipoleObject *)self;
    const PyVL_MultipoleObject *b = (const PyVL_MultipoleObject *)other;

    bool eq = true;
    if (a->multipole.order != b->multipole.order)
        eq = false;

    if (eq)
    {
        const real3_t dc = real3_sub(a->multipole.center, b->multipole.center);
        if (real3_dot(dc, dc) > 1e-20)
            eq = false;
    }

    if (eq)
    {
        const size_t n = multipole_num_coeffs(a->multipole.order);
        if (memcmp(a->coeff_buffer, b->coeff_buffer, sizeof(double) * 3 * n) != 0)
            eq = false;
    }

    const bool result = (op == Py_EQ) ? eq : !eq;
    if (result)
        Py_RETURN_TRUE;
    Py_RETURN_FALSE;
}

/*
 * ----------------------------------------------------------------
 *  Properties: order (read-only), center (read-write)
 * ----------------------------------------------------------------
 */

static PyObject *pyvl_multipole_get_order(PyObject *self, void *Py_UNUSED(closure))
{
    const PyVL_MultipoleObject *this = (const PyVL_MultipoleObject *)self;
    return PyLong_FromUnsignedLong(this->multipole.order);
}

static PyObject *pyvl_multipole_get_center(PyObject *self, void *Py_UNUSED(closure))
{
    const PyVL_MultipoleObject *this = (const PyVL_MultipoleObject *)self;
    PyArrayObject *out = (PyArrayObject *)PyArray_SimpleNew(1, (const npy_intp[1]){3}, NPY_DOUBLE);
    if (!out)
        return NULL;
    double *data = PyArray_DATA(out);
    data[0] = this->multipole.center.x;
    data[1] = this->multipole.center.y;
    data[2] = this->multipole.center.z;
    return (PyObject *)out;
}

static int pyvl_multipole_set_center(PyObject *self, PyObject *value, void *Py_UNUSED(closure))
{
    PyVL_MultipoleObject *this = (PyVL_MultipoleObject *)self;
    if (!value)
    {
        PyErr_SetString(PyExc_TypeError, "Cannot delete the center property.");
        return -1;
    }
    if (!pyvl_veclike3_to_real3(value, &this->multipole.center))
        return -1;
    return 0;
}

static PyGetSetDef pyvl_multipole_getset[] = {
    {
        .name = "order",
        .get = pyvl_multipole_get_order,
        .doc = "int : Order of the multipole expansion.",
    },
    {
        .name = "center",
        .get = pyvl_multipole_get_center,
        .set = pyvl_multipole_set_center,
        .doc = "(3,) array : Center of the multipole expansion.",
    },
    {0},
};

/*
 * ----------------------------------------------------------------
 *  Method helpers
 * ----------------------------------------------------------------
 */

/*
 * ----------------------------------------------------------------
 *  eval(self, points, out=None)
 * ----------------------------------------------------------------
 */

PyDoc_STRVAR(pyvl_multipole_eval_doc,
             "eval(points: ArrayLike, out: npt.NDArray[np.double] | None = None, /) -> npt.NDArray[np.double]\n"
             "Evaluate the multipole expansion at one or more points.\n"
             "\n"
             "Parameters\n"
             "----------\n"
             "points : (..., 3) array_like\n"
             "    Points at which to evaluate. All leading dimensions are preserved in the output.\n"
             "out : (..., 3) ndarray, optional\n"
             "    Output array. Must have the same shape as ``points``, be writable,\n"
             "    C-contiguous, and aligned.\n"
             "\n"
             "Returns\n"
             "-------\n"
             "(..., 3) ndarray\n"
             "    Induced vector at each point.\n"
             "\n"
             "Examples\n"
             "--------\n"
             ">>> import numpy as np\n"
             ">>> from pyvl.cvl import Multipole\n"
             ">>> m = Multipole(0, (0., 0., 0.))\n"
             ">>> m.eval(np.array([[1., 0., 0.]]))\n"
             "array([[0., 0., 0.]])\n");

static PyObject *pyvl_multipole_eval(PyObject *self, PyTypeObject *defining_class, PyObject *const *args,
                                     const Py_ssize_t nargs, const PyObject *kwnames)
{
    const PyVL_MultipoleObject *this;
    const module_state_t *state;
    if (!ensure_multipole_and_state(defining_class, self, &this, &state))
        return NULL;

    PyObject *points_obj;
    PyArrayObject *out = NULL;
    if (parse_arguments_check(
            (cpyutl_argument_t[]){
                {.type = CPYARG_TYPE_PYTHON, .p_val = (void *)&points_obj, .kwname = "points"},
                {.type = CPYARG_TYPE_PYTHON,
                 .p_val = (void *)&out,
                 .kwname = "out",
                 .optional = true,
                 .type_check = &PyArray_Type},
                {0},
            },
            args, nargs, kwnames) < 0)
        return NULL;

    size_t n_points;
    PyArrayObject *points_arr = pyvl_flatten_points(points_obj, &n_points);
    if (!points_arr)
        return NULL;

    const int ndim = PyArray_NDIM(points_arr);
    const npy_intp *dims = PyArray_DIMS(points_arr);

    if (out)
    {
        if (check_input_array(out, ndim, dims, NPY_DOUBLE,
                              NPY_ARRAY_C_CONTIGUOUS | NPY_ARRAY_WRITEABLE | NPY_ARRAY_ALIGNED, "out") < 0)
        {
            Py_DECREF(points_arr);
            return NULL;
        }
        Py_INCREF(out);
    }
    else
    {
        out = (PyArrayObject *)PyArray_SimpleNew(ndim, dims, NPY_DOUBLE);
        if (!out)
        {
            Py_DECREF(points_arr);
            return NULL;
        }
    }

    const real3_t *points_data = (const real3_t *)PyArray_DATA(points_arr);
    real3_t *out_data = (real3_t *)PyArray_DATA(out);

    const multipole_t *mp = &this->multipole;

    Py_BEGIN_ALLOW_THREADS;
    for (size_t i = 0; i < n_points; ++i)
    {
        out_data[i] = multipole_eval(mp, points_data[i]);
    }
    Py_END_ALLOW_THREADS;

    Py_DECREF(points_arr);
    return (PyObject *)out;
}

/*
 * ----------------------------------------------------------------
 *  shift(self, center, work_order=None)
 * ----------------------------------------------------------------
 */

PyDoc_STRVAR(pyvl_multipole_shift_doc,
             "shift(center: VecLike3, work_order: int | None = None, /) -> Multipole\n"
             "Create a new Multipole at *center* with coefficients shifted from this one.\n"
             "\n"
             "The new expansion has the same order as this one.\n"
             "\n"
             "Parameters\n"
             "----------\n"
             "center : VecLike3\n"
             "    Center of the new multipole expansion.\n"
             "work_order : int, optional\n"
             "    Internal expansion order for the binomial series (defaults to ``self.order``).\n"
             "\n"
             "Returns\n"
             "-------\n"
             "Multipole\n"
             "    New multipole expansion at the requested center.\n"
             "\n"
             "See Also\n"
             "--------\n"
             "shift_to : Shift to match another Multipole's center.\n"
             "\n"
             "Examples\n"
             "--------\n"
             ">>> from pyvl.cvl import Multipole\n"
             ">>> m = Multipole(2, (0., 0., 0.))\n"
             ">>> m2 = m.shift((1., 0., 0.))\n"
             ">>> m2.center\n"
             "array([1., 0., 0.])\n");

static PyObject *pyvl_multipole_shift(PyObject *self, PyTypeObject *defining_class, PyObject *const *args,
                                      const Py_ssize_t nargs, const PyObject *kwnames)
{
    const PyVL_MultipoleObject *this;
    const module_state_t *state;
    if (!ensure_multipole_and_state(defining_class, self, &this, &state))
        return NULL;

    PyObject *center_obj;
    Py_ssize_t work_order = -1; // -1 means unset
    if (parse_arguments_check(
            (cpyutl_argument_t[]){
                {.type = CPYARG_TYPE_PYTHON, .p_val = (void *)&center_obj, .kwname = "center"},
                {.type = CPYARG_TYPE_SSIZE, .p_val = &work_order, .kwname = "work_order", .optional = true},
                {0},
            },
            args, nargs, kwnames) < 0)
        return NULL;

    real3_t new_center;
    if (!pyvl_veclike3_to_real3(center_obj, &new_center))
        return NULL;

    const unsigned in_order = this->multipole.order;
    const unsigned out_order = in_order;
    const unsigned wo = (work_order < 0) ? out_order : (unsigned)work_order;

    if (wo < in_order || wo < out_order)
    {
        PyErr_SetString(PyExc_ValueError, "work_order must be >= both input and output orders.");
        return NULL;
    }

    // Allocate the new Multipole
    PyVL_MultipoleObject *out = (PyVL_MultipoleObject *)state->multipole_type->tp_alloc(state->multipole_type, 0);
    if (!out)
        return NULL;

    out->multipole.order = out_order;
    out->multipole.center = new_center;
    out->coeff_buffer = pyvl_allocate_coeffs(out_order, &out->multipole);
    if (!out->coeff_buffer)
    {
        Py_DECREF(out);
        return NULL;
    }

    // Work buffers
    const size_t shift_dim = (size_t)wo + 1;
    const size_t shift_plane = shift_dim * shift_dim;
    const size_t n_coeffs = multipole_num_coeffs(wo);

    double *shift_exp = (double *)PyMem_Malloc(sizeof(double) * 3 * shift_plane);
    double *pse = (double *)PyMem_Malloc(sizeof(double) * 2 * n_coeffs);
    if (!shift_exp || !pse)
    {
        PyMem_Free(pse);
        PyMem_Free(shift_exp);
        Py_DECREF(out);
        PyErr_NoMemory();
        return NULL;
    }

    multipole_add_shift(&this->multipole, &out->multipole, wo, shift_exp, pse);

    PyMem_Free(pse);
    PyMem_Free(shift_exp);
    return (PyObject *)out;
}

/*
 * ----------------------------------------------------------------
 *  shift_to(self, other, work_order=None)
 * ----------------------------------------------------------------
 */

PyDoc_STRVAR(pyvl_multipole_shift_to_doc,
             "shift_to(other: Multipole, work_order: int | None = None, /) -> Multipole\n"
             "Create a new Multipole at *other*\\'s center with coefficients shifted from this one.\n"
             "\n"
             "The new expansion has the same order as this one.\n"
             "\n"
             "Parameters\n"
             "----------\n"
             "other : Multipole\n"
             "    The target multipole whose center is used as the destination.\n"
             "work_order : int, optional\n"
             "    Internal expansion order for the binomial series (defaults to ``self.order``).\n"
             "\n"
             "Returns\n"
             "-------\n"
             "Multipole\n"
             "    New multipole expansion at the requested center.\n"
             "\n"
             "See Also\n"
             "--------\n"
             "shift : Shift to an arbitrary center.\n"
             "\n"
             "Examples\n"
             "--------\n"
             ">>> from pyvl.cvl import Multipole\n"
             ">>> m = Multipole(2, (0., 0., 0.))\n"
             ">>> other = Multipole(2, (1., 0., 0.))\n"
             ">>> m2 = m.shift_to(other)\n"
             ">>> m2.center\n"
             "array([1., 0., 0.])\n"
             "\n"
             "Shift a multipole a large distance and compare the field before\n"
             "and after the shift:\n"
             "\n"
             ".. jupyter-execute::\n"
             "\n"
             "    >>> import matplotlib.pyplot as plt\n"
             "    >>> import numpy as np\n"
             "    >>> from pyvl.cvl import Multipole\n"
             "    >>>\n"
             "    >>> rng = np.random.default_rng(1)\n"
             "    >>> pts = rng.uniform(-0.1, 0.1, size=(10, 3))\n"
             "    >>> vals = rng.uniform(-1, 1, size=(10, 3))\n"
             "    >>> mp = Multipole.from_sources(2, (0., 0., 0.), pts, vals)\n"
             "    >>>\n"
             "    >>> x = y = np.linspace(-5, 5, 100)\n"
             "    >>> xs, ys = np.meshgrid(x, y)\n"
             "    >>> pts_eval = np.stack([xs.ravel(), ys.ravel(),\n"
             "    ...                      np.zeros_like(xs.ravel())], axis=-1)\n"
             "    >>> v_before = mp.eval(pts_eval)\n"
             "    >>>\n"
             "    >>> target = Multipole(2, (2., 0., 0.))\n"
             "    >>> mp_shifted = mp.shift_to(target)\n"
             "    >>> v_after = mp_shifted.eval(pts_eval)\n"
             "    >>>\n"
             "    >>> fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n"
             "    >>> mag_before = np.log10(np.maximum(\n"
             "    ...     np.linalg.norm(v_before, axis=-1), 1e-30))\n"
             "    >>> c1 = ax1.contourf(xs, ys, mag_before.reshape(xs.shape),\n"
             "    ...                    levels=20, cmap=\"viridis\")\n"
             "    >>> _ = ax1.set(title=\"Before shift (centre at origin)\",\n"
             "    ...         xlabel=\"$x$\", ylabel=\"$y$\")\n"
             "    >>> _ = fig.colorbar(c1, ax=ax1)\n"
             "    >>> mag_after = np.log10(np.maximum(\n"
             "    ...     np.linalg.norm(v_after, axis=-1), 1e-30))\n"
             "    >>> c2 = ax2.contourf(xs, ys, mag_after.reshape(xs.shape),\n"
             "    ...                    levels=c1.levels, cmap=\"viridis\")\n"
             "    >>> _ = ax2.set(title=\"After shift_to((2,0,0))\",\n"
             "    ...         xlabel=\"$x$\", ylabel=\"$y$\")\n"
             "    >>> _ = fig.colorbar(c2, ax=ax2)\n"
             "    >>> plt.show()\n");

static PyObject *pyvl_multipole_shift_to(PyObject *self, PyTypeObject *defining_class, PyObject *const *args,
                                         const Py_ssize_t nargs, const PyObject *kwnames)
{
    const PyVL_MultipoleObject *this;
    const module_state_t *state;
    if (!ensure_multipole_and_state(defining_class, self, &this, &state))
        return NULL;

    PyObject *other_obj;
    Py_ssize_t work_order = -1;
    if (parse_arguments_check(
            (cpyutl_argument_t[]){
                {.type = CPYARG_TYPE_PYTHON, .p_val = (void *)&other_obj},
                {.type = CPYARG_TYPE_SSIZE, .p_val = &work_order, .optional = true},
                {0},
            },
            args, nargs, kwnames) < 0)
        return NULL;

    if (!PyObject_TypeCheck(other_obj, state->multipole_type))
    {
        PyErr_Format(PyExc_TypeError, "Argument must be a %s, but was %s.", state->multipole_type->tp_name,
                     Py_TYPE(other_obj)->tp_name);
        return NULL;
    }
    const PyVL_MultipoleObject *other = (const PyVL_MultipoleObject *)other_obj;

    // Reuse shift by constructing a center argument
    const real3_t c = other->multipole.center;
    PyObject *center_tuple = Py_BuildValue("(ddd)", c.x, c.y, c.z);
    if (!center_tuple)
        return NULL;

    // Build args for shift: (center, [work_order])
    PyObject *shift_args[2];
    shift_args[0] = center_tuple;
    Py_ssize_t shift_nargs = 1;
    if (work_order >= 0)
    {
        shift_args[1] = PyLong_FromSsize_t(work_order);
        if (!shift_args[1])
        {
            Py_DECREF(center_tuple);
            return NULL;
        }
        shift_nargs = 2;
    }

    PyObject *result = pyvl_multipole_shift(self, defining_class, shift_args, shift_nargs, NULL);
    Py_DECREF(center_tuple);
    if (work_order >= 0)
        Py_DECREF(shift_args[1]);
    return result;
}

/*
 * ----------------------------------------------------------------
 *  add_sources(self, points, values)
 * ----------------------------------------------------------------
 */

PyDoc_STRVAR(pyvl_multipole_add_sources_doc,
             "add_sources(points: ArrayLike, values: ArrayLike, /) -> None\n"
             "Add source contributions to this multipole expansion.\n"
             "\n"
             "Parameters\n"
             "----------\n"
             "points : (..., 3) array_like\n"
             "    Positions of the sources.\n"
             "values : (..., 3) array_like\n"
             "    Vector values of the sources (must have the same batch shape as points).\n"
             "\n"
             "Examples\n"
             "--------\n"
             ">>> import numpy as np\n"
             ">>> from pyvl.cvl import Multipole\n"
             ">>> m = Multipole(2, (0., 0., 0.))\n"
             ">>> m.add_sources(np.array([[1., 0., 0.]]), np.array([[0., 1., 0.]]))\n");

static PyObject *pyvl_multipole_add_sources(PyObject *self, PyTypeObject *defining_class, PyObject *const *args,
                                            const Py_ssize_t nargs, const PyObject *kwnames)
{
    PyVL_MultipoleObject *this;
    const module_state_t *state;
    if (!ensure_multipole_and_state(defining_class, self, (const PyVL_MultipoleObject **)&this, &state))
        return NULL;

    PyObject *points_obj, *values_obj;
    if (parse_arguments_check(
            (cpyutl_argument_t[]){
                {.type = CPYARG_TYPE_PYTHON, .p_val = (void *)&points_obj},
                {.type = CPYARG_TYPE_PYTHON, .p_val = (void *)&values_obj},
                {0},
            },
            args, nargs, kwnames) < 0)
        return NULL;

    size_t n_points, n_values;
    PyArrayObject *points_arr = pyvl_flatten_points(points_obj, &n_points);
    if (!points_arr)
        return NULL;
    PyArrayObject *values_arr = pyvl_flatten_points(values_obj, &n_values);
    if (!values_arr)
    {
        Py_DECREF(points_arr);
        return NULL;
    }

    if (n_points != n_values)
    {
        PyErr_Format(PyExc_ValueError, "Number of points (%zu) does not match number of values (%zu).", n_points,
                     n_values);
        Py_DECREF(points_arr);
        Py_DECREF(values_arr);
        return NULL;
    }

    const real3_t *points_data = (const real3_t *)PyArray_DATA(points_arr);
    const real3_t *values_data = (const real3_t *)PyArray_DATA(values_arr);

    const unsigned order = this->multipole.order;
    const size_t scratch = multipole_scratch_size(order);

    // Allocate scratch buffers on heap (safe for any order)
    double *cur = (double *)PyMem_Malloc(scratch * sizeof(double));
    double *nxt = (double *)PyMem_Malloc(scratch * sizeof(double));
    if (!cur || !nxt)
    {
        PyMem_Free(nxt);
        PyMem_Free(cur);
        Py_DECREF(points_arr);
        Py_DECREF(values_arr);
        PyErr_NoMemory();
        return NULL;
    }

    for (size_t i = 0; i < n_points; ++i)
    {
        memset(cur, 0, scratch * sizeof(double));
        memset(nxt, 0, scratch * sizeof(double));
        multipole_update(&this->multipole, this->multipole.center, points_data[i], values_data[i], cur, nxt);
    }

    PyMem_Free(nxt);
    PyMem_Free(cur);
    Py_DECREF(points_arr);
    Py_DECREF(values_arr);
    Py_RETURN_NONE;
}

/*
 * ----------------------------------------------------------------
 *  from_sources(cls, order, center, points, values)  -- classmethod
 * ----------------------------------------------------------------
 */

PyDoc_STRVAR(pyvl_multipole_from_sources_doc,
             "from_sources(order: int, center: VecLike3, points: ArrayLike, values: ArrayLike, /) -> Multipole\n"
             "Create a multipole expansion from a set of source points.\n"
             "\n"
             "Parameters\n"
             "----------\n"
             "order : int\n"
             "    Order of the multipole expansion.\n"
             "center : VecLike3\n"
             "    Center of the expansion.\n"
             "points : (..., 3) array_like\n"
             "    Positions of the source particles.\n"
             "values : (..., 3) array_like\n"
             "    Vector values of the source particles.\n"
             "\n"
             "Returns\n"
             "-------\n"
             "Multipole\n"
             "    New multipole expansion with sources built in.\n"
             "\n"
             "Examples\n"
             "--------\n"
             ">>> import numpy as np\n"
             ">>> from pyvl.cvl import Multipole\n"
             ">>> pts = np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]])\n"
             ">>> vals = np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]])\n"
             ">>> m = Multipole.from_sources(2, (0., 0., 0.), pts, vals)\n"
             ">>> m.order\n"
             "2\n");

static PyObject *pyvl_multipole_from_sources(PyTypeObject *type, PyObject *const *args, const Py_ssize_t nargs,
                                             const PyObject *kwnames)
{
    const module_state_t *state = get_module_state(type);
    if (!state)
        return NULL;

    Py_ssize_t order;
    PyObject *center_obj, *points_obj, *values_obj;
    if (parse_arguments_check(
            (cpyutl_argument_t[]){
                {.type = CPYARG_TYPE_SSIZE, .p_val = &order},
                {.type = CPYARG_TYPE_PYTHON, .p_val = (void *)&center_obj},
                {.type = CPYARG_TYPE_PYTHON, .p_val = (void *)&points_obj},
                {.type = CPYARG_TYPE_PYTHON, .p_val = (void *)&values_obj},
                {0},
            },
            args, nargs, kwnames) < 0)
        return NULL;

    real3_t center;
    if (!pyvl_veclike3_to_real3(center_obj, &center))
        return NULL;

    size_t n_pts, n_vals;
    PyArrayObject *points_arr = pyvl_flatten_points(points_obj, &n_pts);
    if (!points_arr)
        return NULL;
    PyArrayObject *values_arr = pyvl_flatten_points(values_obj, &n_vals);
    if (!values_arr)
    {
        Py_DECREF(points_arr);
        return NULL;
    }

    if (n_pts != n_vals)
    {
        PyErr_Format(PyExc_ValueError, "Number of points (%zu) does not match number of values (%zu).", n_pts, n_vals);
        Py_DECREF(points_arr);
        Py_DECREF(values_arr);
        return NULL;
    }

    if (order < 0)
    {
        PyErr_SetString(PyExc_ValueError, "Order must be non-negative.");
        return NULL;
    }
    const unsigned uorder = (unsigned)order;

    const size_t n_coeffs = multipole_num_coeffs(uorder);
    const size_t scratch = multipole_scratch_size(uorder);
    // multipole_create checks: num_coeffs >= max(3 * n_coeffs, scratch)
    const size_t coeff_buf_size = 3 * n_coeffs;
    const size_t num_coeffs_for_create = (coeff_buf_size > scratch) ? coeff_buf_size : scratch;

    // We allocate a single block: 3*n_coeffs for coeffs + 2*scratch for cur/nxt
    double *coeffs = (double *)PyMem_Malloc(sizeof(double) * (coeff_buf_size + 2 * scratch));
    double *cur = coeffs + coeff_buf_size;
    double *nxt = cur + scratch;
    if (!coeffs)
    {
        Py_DECREF(points_arr);
        Py_DECREF(values_arr);
        PyErr_NoMemory();
        return NULL;
    }

    const real3_t *points_data = (const real3_t *)PyArray_DATA(points_arr);
    const real3_t *values_data = (const real3_t *)PyArray_DATA(values_arr);

    multipole_t mp;

    // Zero scratch areas before calling create
    memset(cur, 0, scratch * sizeof(double));
    memset(nxt, 0, scratch * sizeof(double));

    const bool ok = multipole_create(uorder, (unsigned)num_coeffs_for_create, coeffs, center, (unsigned)n_pts,
                                     points_data, values_data, cur, nxt, &mp);
    Py_DECREF(points_arr);
    Py_DECREF(values_arr);

    if (!ok)
    {
        PyMem_Free(coeffs);
        PyErr_SetString(PyExc_RuntimeError, "multipole_create failed.");
        return NULL;
    }

    // Build the Python object, transfer ownership of coeffs
    PyVL_MultipoleObject *self = (PyVL_MultipoleObject *)type->tp_alloc(type, 0);
    if (!self)
    {
        PyMem_Free(coeffs);
        return NULL;
    }

    self->multipole = mp;
    self->multipole.order = uorder;
    self->coeff_buffer = coeffs; // coeffs_x/y/z already point inside this buffer

    return (PyObject *)self;
}

/*
 * ----------------------------------------------------------------
 *  Method table & type spec
 * ----------------------------------------------------------------
 */

static PyMethodDef pyvl_multipole_methods[] = {
    {
        .ml_name = "eval",
        .ml_meth = (void *)pyvl_multipole_eval,
        .ml_flags = METH_METHOD | METH_KEYWORDS | METH_FASTCALL,
        .ml_doc = pyvl_multipole_eval_doc,
    },
    {
        .ml_name = "shift",
        .ml_meth = (void *)pyvl_multipole_shift,
        .ml_flags = METH_METHOD | METH_KEYWORDS | METH_FASTCALL,
        .ml_doc = pyvl_multipole_shift_doc,
    },
    {
        .ml_name = "shift_to",
        .ml_meth = (void *)pyvl_multipole_shift_to,
        .ml_flags = METH_METHOD | METH_KEYWORDS | METH_FASTCALL,
        .ml_doc = pyvl_multipole_shift_to_doc,
    },
    {
        .ml_name = "add_sources",
        .ml_meth = (void *)pyvl_multipole_add_sources,
        .ml_flags = METH_METHOD | METH_KEYWORDS | METH_FASTCALL,
        .ml_doc = pyvl_multipole_add_sources_doc,
    },
    {
        .ml_name = "from_sources",
        .ml_meth = (void *)pyvl_multipole_from_sources,
        .ml_flags = METH_CLASS | METH_KEYWORDS | METH_FASTCALL,
        .ml_doc = pyvl_multipole_from_sources_doc,
    },
    {0},
};

PyType_Spec pyvl_multipole_typespec = {
    .name = PYVL_CTYPE_NAME(Multipole),
    .basicsize = sizeof(PyVL_MultipoleObject),
    .itemsize = 0,
    .flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_IMMUTABLETYPE | Py_TPFLAGS_HAVE_GC | Py_TPFLAGS_HEAPTYPE,
    .slots =
        (PyType_Slot[]){
            {Py_tp_str, pyvl_multipole_str},
            {Py_tp_repr, pyvl_multipole_repr},
            {Py_tp_doc, (void *)pyvl_multipole_type_docstring},
            {Py_tp_methods, pyvl_multipole_methods},
            {Py_tp_getset, pyvl_multipole_getset},
            {Py_tp_new, pyvl_multipole_new},
            {Py_tp_dealloc, pyvl_multipole_dealloc},
            {Py_tp_richcompare, pyvl_multipole_rich_compare},
            {Py_tp_traverse, cpyutl_traverse_heap_type},
            {0},
        },
};
