#!/usr/bin/env python3
"""
Generate cvl_cl_kernel_sources.h - embedded OpenCL C kernel sources.

Each "pack" (see cvl_cl_pack_t in cvl_cl_compute.h) is assembled from a
.cl.h file (or include chain) in src/core/opencl by:
  1. stripping `#include` and `#pragma once` lines (OpenCL C cannot
     resolve them at build time),
  2. prepending a precision-switching preamble (real_t / real3_t,
     plus uint64_t / size_t where the shared headers need them).

The generated header defines one static const char[] per pack plus a
table mapping cvl_cl_pack_t -> source string, so cvl_cl_compute_init
can compile programs without any runtime file I/O.

Run via CMake (add_custom_command) - invoked from the build directory.
"""

import argparse
import os

# Preamble for self-contained packs (bh_build, bh_flat_eval, direct_sum).
PREAMBLE_BH = """#ifdef CVL_CL_REAL_FP32
typedef float real_t;
typedef struct { real_t x, y, z; } real3_t;
#else
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
typedef double real_t;
typedef struct { real_t x, y, z; } real3_t;
#endif

"""

# Preamble for the shared-header chain (types -> math -> multipole ->
# multipole_ops -> fmm_ops -> fmm_l2p).  cvl_cl_types.h.cl provides
# real3_t and the real3 helpers; uint64_t / size_t are host typedefs
# that OpenCL C does not provide by default.
PREAMBLE_FMM = """#ifdef CVL_CL_REAL_FP32
typedef float real_t;
#else
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
typedef double real_t;
#endif

typedef unsigned long uint64_t;
typedef unsigned long size_t;

"""

# Pack name -> (preamble, ordered file list).  Order matters for the
# shared-header chain.
PACKS = [
    ("CVL_CL_SRC_BH_BUILD", PREAMBLE_BH, ["bh_build.cl.h"]),
    ("CVL_CL_SRC_BH_EVAL", PREAMBLE_BH, ["bh_flat_eval.cl.h"]),
    (
        "CVL_CL_SRC_FMM_EVAL",
        PREAMBLE_FMM,
        [
            "cvl_cl_types.h.cl",
            "cvl_cl_math.h.cl",
            "cvl_cl_multipole.h.cl",
            "cvl_cl_multipole_ops.h.cl",
            "cvl_cl_fmm_ops.h.cl",
            "fmm_l2p.cl.h",
        ],
    ),
    ("CVL_CL_SRC_DIRECT_SUM", PREAMBLE_BH, ["direct_sum.cl.h"]),
]


def strip_header(source):
    """Remove #include and #pragma once lines (same as the tests' skip_include_concat)."""
    out = []
    for line in source.splitlines(keepends=True):
        trimmed = line.lstrip()
        if trimmed.startswith("#include") or trimmed.startswith("#pragma once"):
            continue
        out.append(line)
    return "".join(out)


def load(source_dir, name):
    """Load a source file from the given directory."""
    with open(os.path.join(source_dir, name), "r", encoding="utf-8") as f:
        return f.read()


def c_escape(text):
    """Escape a raw chunk of source for use inside a C string literal."""
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    return "".join(out)


def chunked_literals(text, width=80):
    """Split raw text into C string literals.

    Escaping is per-chunk so escape sequences never straddle a literal boundary.
    """
    return "\n".join(
        '    "%s"' % c_escape(text[i : i + width]) for i in range(0, len(text), width)
    )


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--source-dir", required=True, help="Directory containing the .cl.h files."
    )
    ap.add_argument("--output", required=True, help="Generated header path.")
    args = ap.parse_args()

    bodies = []
    for name, preamble, files in PACKS:
        body = preamble + "".join(strip_header(load(args.source_dir, f)) for f in files)
        bodies.append((name, body))

    lines = [
        "/* Generated by gen_kernel_sources.py. Do not edit. */",
        "#pragma once",
        "",
    ]
    for name, body in bodies:
        lines.append("static const char %s[] =" % name)
        lines.append(chunked_literals(body))
        lines.append("    ;")
        lines.append("")

    lines.append("/* Pack index -> assembled source (indexed by cvl_cl_pack_t). */")
    lines.append("static const char *const CVL_CL_PACK_SOURCES[CVL_CL_PACK_COUNT] = {")
    for i, (name, _) in enumerate(bodies):
        lines.append("    [%d] = %s," % (i, name))
    lines.append("};")
    lines.append("")

    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
